### ISSUE TITLE
Calculation of kmer_types

### ISSUE THREAD

**Issue by eselimnl** [PU-SDS/hunana#7]
kmer_types defined as: A measure of distinct variant sequences. Currently HUNANA does not provide kmer_types (e.g. nonatypes) incidence but total number of distinct variant sequences.

It would be useful if HUNANA calculates the incidence of kmer_types for a given position as follows:

For a given position calculation can easily made by:

[total number of distinct variant sequences] - 1 (index is not count as distinct) _divided by_ [total number of variants (supports)], [multiply to 100]

**Comment by ShanWeera** [comment]
The current version gives a list of distinct k-mers at a particular position.
```
[
  {
    "position": 1,
    "entropy": 0.0,
    "supports": 2,
    "sequences": [
      {
        "position": 1,
        "sequence": "MASPGLHLL",
        "count": 2,
        "conservation": 100.0,
        "motif_short": "I",
        "motif_long": "Index"
      }
    ],
    "variants": 1,
    "kmertypes: [
      'MASPGLHLL'
    ]
  }
]
```

What you are suggesting is in addition to this?

**Comment by ShanWeera** [comment]
> kmer_types defined as: A measure of distinct variant sequences. Currently HUNANA does not provide kmer_types (e.g. nonatypes) incidence but total number of distinct variant sequences.
> 
> 
> 
> It would be useful if HUNANA calculates the incidence of kmer_types for a given position as follows:
> 
> 
> 
> For a given position calculation can easily made by:
> 
> 
> 
> [total number of distinct variant sequences] - 1 (index is not count as distinct) _divided by_ [total number of variants (supports)], [multiply to 100]


The current version gives a list of distinct k-mers at a particular position.
```
[
  {
    "position": 1,
    "entropy": 0.0,
    "supports": 2,
    "sequences": [
      {
        "position": 1,
        "sequence": "MASPGLHLL",
        "count": 2,
        "conservation": 100.0,
        "motif_short": "I",
        "motif_long": "Index"
      }
    ],
    "variants": 1,
    "kmertypes: [
      'MASPGLHLL'
    ]
  }
]
```

What you are suggesting is in addition to this?

**Comment by eselimnl** [comment]
First, instead of calling "variants", you may say "kmertypes_incidence"

Second, instead of giving number of k-mers, give the incidence of k-mers (current calculation of "variants"/ supports*100). Before that please remove the index variant (current calculation minus 1).

**Comment by ShanWeera** [comment]
> First, instead of calling "variants", you may say "kmertypes_incidence"
> 
> 
> 
> Second, instead of giving number of k-mers, give the incidence of k-mers (current calculation of "variants"/ supports*100). Before that please remove the index variant (current calculation minus 1).  Looking for the given example, kmertype_incidence should be : (1-1/2)*100 = 0%

I think something like the below example could be a lot cleaner and easy to understand.
```
[
  {
    "position":1,
    "entropy":0.0,
    "supports":2,
    "sequences":[
      {
        "position":1,
        "sequence":"MASPGLHLL",
        "count":2,
        "conservation":100.0,
        "motif_short":"I",
        "motif_long":"Index"
      }
    ],
    "kmer_types":{
      "incidence":12.0,
      "types":[
        "MASPGLHLL"
      ]
    }
  }
]
```
Let me know what you think.

**Comment by ShanWeera** [comment]
> First, instead of calling "variants", you may say "kmertypes_incidence"
> 
> Second, instead of giving number of k-mers, give the incidence of k-mers (current calculation of "variants"/ supports*100). Before that please remove the index variant (current calculation minus 1). Looking for the given example, kmertype_incidence should be : (1-1/2)*100 = 0%

As we discussed, I see a few issues with the current version:

1. In the current version, the list of 'kmertypes" includes the Index. According to Hadia' (Hadia et al, 2020) paper on which Hunana is based, Index should not be included in the list of "kmertypes"
2. Current version does not calculate "kmertype" incidence. This is needed downstream in the VADA module.
3. The key name "kmertypes" should probably be changed to "kmer_types" for better readability.

Am I getting everything right?. Is there anything else that we need to address?

_Abd Raman, H. S., Tan, S., August, J. T., & Khan, A. M. (2020). Dynamics of Influenza A (H5N1) virus protein sequence diversity. PeerJ, 7, e7954._

**Comment by eselimnl** [comment]
You have addressed all of my concerns, nothing left. 

Thanks
